language: haskell

ghc:
  - 7.8
  - 7.6

install:
  - sudo add-apt-repository -y ppa:yandex-sysmon/zookeeper-3.4
  - sudo apt-get update
  - sudo apt-get -y --force-yes install dnsutils
  - sudo apt-get -y --force-yes install libzookeeper-mt-dev zookeeperd libsqlite3-dev
  - cabal update
  - cabal install -j --only-dep --enable-tests --force-reinstalls --reorder-goals

script:
  - cabal configure --enable-tests && cabal build && cabal test

